Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\Admin\anaconda3\Lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\anaconda3\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\anaconda3\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Admin\anaconda3\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Admin\anaconda3\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Admin\anaconda3\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# This code reads just one sheet from a Google Sheet which may contain multiple sheets
#import pandas as pd
#sheet_id = "1OCqC9k0lz1kRZ-RXYRMgI8ebjHum1xHEfAYKl4t3Nos"
#df = pd.read_csv(f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv")

# This code reads all multiple sheets from a Google Sheet
import openpyxl
import pandas as pd
import requests
from io import BytesIO
from IPython.display import display, Markdown

spreadsheetId = "1OCqC9k0lz1kRZ-RXYRMgI8ebjHum1xHEfAYKl4t3Nos"
url = "https://docs.google.com/spreadsheets/export?exportFormat=xlsx&id=" + spreadsheetId
res = requests.get(url)
data = BytesIO(res.content)
xlsx = openpyxl.load_workbook(filename=data)
for name in xlsx.sheetnames:
    if name == 'Income Statement':
        df = pd.read_excel(data, sheet_name=name)
        break
        
df['Sparkline'] = df.apply(lambda row: sparkline([row[2019], row[2020], row[2021], row[2022], row[2023]]), axis=1)
df = df.set_index(df.columns[0])
df.index.names = ['Field']
display(Markdown(df.to_markdown()))
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mImportError[0m                               Traceback (most recent call last)
Cell [1;32mIn[2], line 20[0m
[0;32m     18[0m [38;5;28;01mfor[39;00m name [38;5;129;01min[39;00m xlsx[38;5;241m.[39msheetnames:
[0;32m     19[0m     [38;5;28;01mif[39;00m name [38;5;241m==[39m [38;5;124m'[39m[38;5;124mIncome Statement[39m[38;5;124m'[39m:
[1;32m---> 20[0m         df [38;5;241m=[39m pd[38;5;241m.[39mread_excel(data, sheet_name[38;5;241m=[39mname)
[0;32m     21[0m         [38;5;28;01mbreak[39;00m
[0;32m     23[0m df[[38;5;124m'[39m[38;5;124mSparkline[39m[38;5;124m'[39m] [38;5;241m=[39m df[38;5;241m.[39mapply([38;5;28;01mlambda[39;00m row: sparkline([row[[38;5;241m2019[39m], row[[38;5;241m2020[39m], row[[38;5;241m2021[39m], row[[38;5;241m2022[39m], row[[38;5;241m2023[39m]]), axis[38;5;241m=[39m[38;5;241m1[39m)

File [1;32m~\anaconda3\Lib\site-packages\pandas\io\excel\_base.py:495[0m, in [0;36mread_excel[1;34m(io, sheet_name, header, names, index_col, usecols, dtype, engine, converters, true_values, false_values, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, parse_dates, date_parser, date_format, thousands, decimal, comment, skipfooter, storage_options, dtype_backend, engine_kwargs)[0m
[0;32m    493[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28misinstance[39m(io, ExcelFile):
[0;32m    494[0m     should_close [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[1;32m--> 495[0m     io [38;5;241m=[39m ExcelFile(
[0;32m    496[0m         io,
[0;32m    497[0m         storage_options[38;5;241m=[39mstorage_options,
[0;32m    498[0m         engine[38;5;241m=[39mengine,
[0;32m    499[0m         engine_kwargs[38;5;241m=[39mengine_kwargs,
[0;32m    500[0m     )
[0;32m    501[0m [38;5;28;01melif[39;00m engine [38;5;129;01mand[39;00m engine [38;5;241m!=[39m io[38;5;241m.[39mengine:
[0;32m    502[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[0;32m    503[0m         [38;5;124m"[39m[38;5;124mEngine should not be specified when passing [39m[38;5;124m"[39m
[0;32m    504[0m         [38;5;124m"[39m[38;5;124man ExcelFile - ExcelFile already has the engine set[39m[38;5;124m"[39m
[0;32m    505[0m     )

File [1;32m~\anaconda3\Lib\site-packages\pandas\io\excel\_base.py:1567[0m, in [0;36mExcelFile.__init__[1;34m(self, path_or_buffer, engine, storage_options, engine_kwargs)[0m
[0;32m   1564[0m [38;5;28mself[39m[38;5;241m.[39mengine [38;5;241m=[39m engine
[0;32m   1565[0m [38;5;28mself[39m[38;5;241m.[39mstorage_options [38;5;241m=[39m storage_options
[1;32m-> 1567[0m [38;5;28mself[39m[38;5;241m.[39m_reader [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_engines[engine](
[0;32m   1568[0m     [38;5;28mself[39m[38;5;241m.[39m_io,
[0;32m   1569[0m     storage_options[38;5;241m=[39mstorage_options,
[0;32m   1570[0m     engine_kwargs[38;5;241m=[39mengine_kwargs,
[0;32m   1571[0m )

File [1;32m~\anaconda3\Lib\site-packages\pandas\io\excel\_openpyxl.py:552[0m, in [0;36mOpenpyxlReader.__init__[1;34m(self, filepath_or_buffer, storage_options, engine_kwargs)[0m
[0;32m    534[0m [38;5;129m@doc[39m(storage_options[38;5;241m=[39m_shared_docs[[38;5;124m"[39m[38;5;124mstorage_options[39m[38;5;124m"[39m])
[0;32m    535[0m [38;5;28;01mdef[39;00m [38;5;21m__init__[39m(
[0;32m    536[0m     [38;5;28mself[39m,
[1;32m   (...)[0m
[0;32m    539[0m     engine_kwargs: [38;5;28mdict[39m [38;5;241m|[39m [38;5;28;01mNone[39;00m [38;5;241m=[39m [38;5;28;01mNone[39;00m,
[0;32m    540[0m ) [38;5;241m-[39m[38;5;241m>[39m [38;5;28;01mNone[39;00m:
[0;32m    541[0m [38;5;250m    [39m[38;5;124;03m"""[39;00m
[0;32m    542[0m [38;5;124;03m    Reader using openpyxl engine.[39;00m
[0;32m    543[0m 
[1;32m   (...)[0m
[0;32m    550[0m [38;5;124;03m        Arbitrary keyword arguments passed to excel engine.[39;00m
[0;32m    551[0m [38;5;124;03m    """[39;00m
[1;32m--> 552[0m     import_optional_dependency([38;5;124m"[39m[38;5;124mopenpyxl[39m[38;5;124m"[39m)
[0;32m    553[0m     [38;5;28msuper[39m()[38;5;241m.[39m[38;5;21m__init__[39m(
[0;32m    554[0m         filepath_or_buffer,
[0;32m    555[0m         storage_options[38;5;241m=[39mstorage_options,
[0;32m    556[0m         engine_kwargs[38;5;241m=[39mengine_kwargs,
[0;32m    557[0m     )

File [1;32m~\anaconda3\Lib\site-packages\pandas\compat\_optional.py:164[0m, in [0;36mimport_optional_dependency[1;34m(name, extra, errors, min_version)[0m
[0;32m    162[0m     [38;5;28;01mreturn[39;00m [38;5;28;01mNone[39;00m
[0;32m    163[0m [38;5;28;01melif[39;00m errors [38;5;241m==[39m [38;5;124m"[39m[38;5;124mraise[39m[38;5;124m"[39m:
[1;32m--> 164[0m     [38;5;28;01mraise[39;00m [38;5;167;01mImportError[39;00m(msg)
[0;32m    165[0m [38;5;28;01melse[39;00m:
[0;32m    166[0m     [38;5;28;01mreturn[39;00m [38;5;28;01mNone[39;00m

[1;31mImportError[0m: Pandas requires version '3.1.0' or newer of 'openpyxl' (version '3.0.10' currently installed).

